<?php
Yii::import('application.extensions.fpdf.*');
require_once("fpdf.php");

$pdf = new fpdf('A4','P','mm');
$pdf->AddPage("P","A4");
$pdf->SetFont('Arial','',11); 
$pdf->Cell(190,10,'Palembang, '.$tgl_cetak,0,0,'R');
$pdf->Ln();
$pdf->Ln();
$pdf->Cell(190,5,'Yth. Bapak Kepala Perwakilan',0,0,'L');
$pdf->Ln();
$pdf->Cell(190,5,'BPKP Provinsi Sumatera Selatan',0,0,'L');
$pdf->Ln();
$pdf->Cell(190,10,'',0,0,'L');
$pdf->Ln();
$pdf->Cell(190,10,'    Yang bertanda tangan di bawah ini:', '', '', 'L');
$pdf->Ln();
$pdf->Cell(45,7,'       Nama', '', '', 'L');$pdf->Cell(3,7,': ', '', '', 'L');;$pdf->Cell(40,7, $list['0']['pegawai_id'], '', '', 'L');
$pdf->Ln();
$pdf->Cell(45,7,'       NIP', '', '', 'L');$pdf->Cell(3,7,': ', '', '', 'L');;$pdf->Cell(40,7,substr($list['0']['NIP'],0,8).' '.substr($list['0']['NIP'],8,6).' '.substr($list['0']['NIP'],14,1).' '.substr($list['0']['NIP'],15,3), '', '', 'L');
$pdf->Ln();
$pdf->Cell(45,7,'       Pangkat/Gol.Ruang', '', '', 'L');$pdf->Cell(3,7,': ', '', '', 'L');;$pdf->Cell(40,7,$list['0']['pangkat'].' / '.$list['0']['gol'].$list['0']['ruang'], '', '', 'L');
$pdf->Ln();
$pdf->Cell(45,7,'       Satuan Organisasi', '', '', 'L');$pdf->Cell(3,7,': ', '', '', 'L');;$pdf->Cell(40,7,'Perwakilan BPKP Provinsi Sumatera Selatan', '', '', 'L');
$pdf->Ln();
$pdf->MultiCell(190,7,'Dengan ini mengajukan permintaan '.$list['0']['cuti_id'].' untuk tahun '.$list['0']['thn_cuti'].' selama '.$list['0']['jml_hari'].' hari kerja, terhitung mulai tanggal '.date('j M Y', strtotime($list['0']['tgl_mulai'])).' s/d '. date('j M Y', strtotime($list['0']['tgl_selesai'])).'.', '', 'L', 0);
$pdf->MultiCell(190,7,'     Selama menjalankan cuti alamat saya adalah di '.$list['0']['alamat'].'.', '', 'L', 0);
$pdf->MultiCell(190,7,"Demikian permintaan ini saya buat untuk dapat dipertimbangkan sebagaimana mestinya.", '', 'L', 0);
$pdf->Ln();
$pdf->SetX(120);
$pdf->MultiCell(60,5,"Hormat Saya,", '', 'C', 0);
$pdf->SetX(120);
$pdf->MultiCell(60,5,"", '', 'C', 0);
$pdf->SetX(120);
$pdf->MultiCell(60,5,"", '', 'C', 0);
$pdf->SetX(120);
$pdf->MultiCell(60,5,$list['0']['pegawai_id'], '', 'C', 0);
$pdf->SetX(120);
$pdf->MultiCell(60,5,'NIP '.substr($list['0']['NIP'],0,8).' '.substr($list['0']['NIP'],8,6).' '.substr($list['0']['NIP'],14,1).' '.substr($list['0']['NIP'],15,3), '', 'C', 0);
$pdf->SetXY(10, 200);
$pdf->MultiCell(95,7,"Catatan Pejabat Kepegawaian", 'LRT', 'L', 0);
$pdf->SetXY(105, 200);
$pdf->MultiCell(95,7,"Catatan / Pertimbangan Atasan Langsung", 'RT', 'L', 0);
$pdf->SetXY(10, 207);
$pdf->MultiCell(95,7,"Cuti yang telah diambil dalam tahun yang ", 'LR', 'L', 0);
$pdf->SetXY(105, 207);
$pdf->MultiCell(95,7,"", 'R', 'L', 0);
$pdf->SetXY(10, 214);
$pdf->MultiCell(95,7,"bersangkutan:", 'LR', 'L', 0);
$pdf->SetXY(105, 214);
$pdf->MultiCell(95,7,"", 'R', 'L', 0);
$pdf->SetXY(10, 221);
$pdf->MultiCell(95,7,"1. Cuti Tahunan", 'LR', 'L', 0);
$pdf->SetXY(105, 221);
$pdf->MultiCell(95,7,"", 'R', 'L', 0);
$pdf->SetXY(10, 228);
$pdf->MultiCell(95,7,"2. Cuti Besar", 'LR', 'L', 0);
$pdf->SetXY(105, 228);
$pdf->MultiCell(95,7,"Keputusan Pejabat yang berwenang memberikan cuti", 'R', 'L', 0);
$pdf->SetXY(10, 235);
$pdf->MultiCell(95,7,"3. Cuti Sakit", 'LR', 'L', 0);
$pdf->SetXY(105, 235);
$pdf->MultiCell(95,7,"", 'R', 'L', 0);
$pdf->SetXY(10, 242);
$pdf->MultiCell(95,7,"4. Cuti Bersalin", 'LR', 'L', 0);
$pdf->SetXY(105, 242);
$pdf->MultiCell(95,7,"", 'R', 'L', 0);
$pdf->SetXY(10, 249);
$pdf->MultiCell(95,7,"5. Cuti Karena Alasan Penting", 'LR', 'L', 0);
$pdf->SetXY(105, 249);
$pdf->MultiCell(95,7,"", 'R', 'L', 0);
$pdf->SetXY(10, 256);
$pdf->MultiCell(95,7,"6. Keterangan lain-lain", 'BLR', 'L', 0);
$pdf->SetXY(105, 256);
$pdf->MultiCell(95,7,"", 'BR', 'L', 0);
$pdf->Output();
Yii::app()->end();


 ?>
